import type { Metadata } from "next";
import { MantineProvider, ColorSchemeScript } from "@mantine/core";

import "./globals.css";
import '@mantine/core/styles.css';
import '@mantine/dates/styles.css';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html >
       <head>
        <ColorSchemeScript />
      </head>
      <body>
      <MantineProvider >
        {children}
      </MantineProvider>
      </body>
    </html>
  );
}
